In [1]:
import numpy as np

In [2]:
vector = np.array([0, 1, 2, 3])
print vector

[0 1 2 3]


In [3]:
matrix_one = np.array([[0, 1], [3, 4]])
print matrix_one

[[0 1]
 [3 4]]


In [7]:
matrix_two = np.array([[[0, 1, 2], [1, 2, 3], [2, 3, 4]]])
matrix_two

array([[[0, 1, 2],
        [1, 2, 3],
        [2, 3, 4]]])

In [18]:
fourbyeight = np.array([range(8), range(8,16), range(16,24), range(24, 32)])
fourbyeight.shape


(4, 8)

In [20]:
np.add(vector, vector)

array([0, 2, 4, 6])

In [27]:
a = range(1,7)
b = range(-6,0)
np.add(a, b)

#or
#a = np.array(range(1,7))
#b = np.array(range(-6,0))
# a+b

[-6, -5, -4, -3, -2, -1]

In [30]:
a = [-1,-2,-3,-4,5,-6]
np.subtract(a,b)

array([ 5,  3,  1, -1,  7, -5])

In [32]:
a = [101, 201, 33.22, -423, 5.3234, -6234]
b = [-601, -501.33, -113, -3.3000003, -2, -1.9999999999999999]
np.subtract(a, b)

array([  702.       ,   702.33     ,   146.22     ,  -419.6999997,
           7.3234   , -6232.       ])

In [38]:
a = [-101, -201, -33.22, 423, -5.3234, -34]
b = [601, -501.33, 113, -3.3000003, 'l', 10.999999999999999]

for index, value in enumerate(b):
#     print index, value
#     print type(value)
    if type(value) == str:
#         print 'found str'
        b[index] = 0

np.subtract(a, b)

array([-702.       ,  300.33     , -146.22     ,  426.3000003,
         -5.3234   ,  -45.       ])