In [1]:
import numpy as np

In [2]:
x = np.array([range(4), range(4,8), range(8,12), range(12,16)])
y = np.array([range(-4,0), range(0,4), range(4,8), range(8,12)])

In [3]:
x.shape, y.shape

((4, 4), (4, 4))

In [4]:
z = np.array([[range(-4,0), range(0,4), range(4,8), range(8,12)], [range(4), range(4,8), range(8,12), range(12,16)]])

In [5]:
z

array([[[-4, -3, -2, -1],
        [ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [6]:
x + y

array([[-4, -2,  0,  2],
       [ 4,  6,  8, 10],
       [12, 14, 16, 18],
       [20, 22, 24, 26]])

In [7]:
x - y

array([[4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4]])

In [8]:
np.dot(x, y)

array([[ 32,  38,  44,  50],
       [ 64,  86, 108, 130],
       [ 96, 134, 172, 210],
       [128, 182, 236, 290]])

In [9]:
a = [[1,2], [0, 1]]
b = [[2,4], [2, 2]]
np.dot(a, b)

array([[6, 8],
       [2, 2]])

In [10]:
# indexing method 2

In [11]:
# indexing method 3

In [12]:
# indexing method 4

In [13]:
# indexing method 5

In [14]:
# indexing method 6